# Generated by Django 4.2.1 on 2023-06-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artical',
            new_name='Article',
        ),
    ]
