# Generated by Django 4.2.1 on 2023-06-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_images_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='key',
        ),
    ]
