# Generated by Django 4.2.1 on 2023-06-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.TextField(default='title'),
        ),
    ]
