# Generated by Django 4.2.1 on 2023-06-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_alter_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
