# Generated by Django 4.2.1 on 2023-06-24 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='article_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
