# Generated by Django 4.2.1 on 2023-06-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_images_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='article_id',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
